### ISSUE TITLE
Octopus CLI Errors Masked; Prevents Troubleshooting

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/create-release-action#318]
Prior to v2, errors from the Octopus CLI were emitted to the output logs. This was helpful when troubleshooting the action execution. In v2, these errors are now masked with the following output emitted to the console:

`Error: Error: Octopus CLI returned an error code. Please check your GitHub actions log for more detail`

This is non-optimal. We should facilitate self-serving of errors by emitting them to the console.

:link: [Example](https://github.com/OctopusDeploy/SupportTools/runs/7342191060?check_suite_focus=true) (private; internal)

**Comment by borland** [comment]
All text output via stdout is still emitted to the log in v2; we don't mask anything, there are just a few lines which it 'reinterprets' to make them look nicer.

E.g. if you look at the build for the action itself when it does the self-test ( https://github.com/OctopusDeploy/create-release-action/runs/7346487660?check_suite_focus=true ) we can see the following:

```
Found environments: 
This Octopus Server supports channels
Found project: project854cae99428161a3edcb6bb[25](https://github.com/OctopusDeploy/create-release-action/runs/7346487660?check_suite_focus=true#step:8:26)6ad2ca3 (Projects-1)
Automatically selecting the best channel for this release...
Building a release plan for Channel 'Default'...
Finding deployment process...
Finding release template...
Selected the release plan for Channel 'Default' - it is a perfect match
Using version number from release template: 0.0.2
```

This is all raw output from the underlying .NET CLI itself.

We don't propagate stderr, but v1 of the action didn't do this either, and the Octopus .NET CLI doesn't seem to use stderr.

I suspect something else is going on with this error report. Perhaps the .NET CLI failed to run and output anything (e.g. a missing dll or .NET runtime error or something to that effect). I will follow up and see what we can find

**Comment by borland** [comment]
Resolution: When running with an older (v7.x) of the octopus CLI, the CLI would fail to launch, returning a process exit code of 159
It would write to stderror explaining what happened, however the action was not propagating either of those things, so we didn't see the information.

Root cause was that v2.0.0 of the action would only pass a stripped-down set of environment variables to the CLI, missing all the standard builtin ones like $HOME and so-on. This worked fine with a newer (v9.x) Octopus CLI built with Dotnet 6, however the older v7.x CLI built with Dotnet Core 3.1 would fail to launch.

v2.0.1 of the action propagates both the process exit code, and stderr messages out to the Github Actions log, making this kind of error visible, and no longer strips the environment, which means both old and newer versions of the CLI now work as expected
